### ISSUE TITLE
💀💀💀 issue with git proxy again

### ISSUE THREAD

**Issue by FearlessOfficial** [Illegal-Services/Illegal_Services#55] opened 2023-12-09 15:31 UTC
![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/00402fd2-6493-4b84-b42c-a4c1af28092d)

💀 I reinstalled it   IS.setup and still same thing i just got lower version
@Illegal-Services 

Sorry about this :< 
Respond later if you like, you can have break

**Comment by Illegal-Services** [comment] 2023-12-09 15:34
Hum oh hey... I do have time don't worry about that first of all ^^

I can see you are still running an outdated version, I wonder why and how this happens... (it's supposed to automatically download and run latest version at launcher)

**Comment by Illegal-Services** [comment] 2023-12-09 15:34
what error message did you run trough in the launcher?

**Comment by FearlessOfficial** [comment] 2023-12-09 15:37
> what error message did you run trough in the launcher?

the same like last time

**Comment by Illegal-Services** [comment] 2023-12-09 15:38
let me review the source code on that error and see what could goes wrong

**Comment by FearlessOfficial** [comment] 2023-12-09 15:38
> let me review the source code on that error and see what could goes wrong

should i send my file that i downloaded? or?

**Comment by Illegal-Services** [comment] 2023-12-09 15:40
nu, no need to, I just have to see which actions fails teorically on your side, I personally reproduced a clean install on my own PC and it worked fine, so there should be some thing on your side failing, now what, I have no idea, and we must work on finding that ahah

**Comment by FearlessOfficial** [comment] 2023-12-09 15:41
> nu, no need to, I just have to see which actions fails teorically on your side, I personally reproduced a clean install on my own PC and it worked fine, so there should be some thing on your side failing, now what, I have no idea, and we must work on finding that ahah

Alrighty :D 
Just so ou know when i got it from friend it worked but when i downloaded the newer version of it then it started happening

**Comment by FearlessOfficial** [comment] 2023-12-09 15:41
https://github.com/Illegal-Services/Illegal_Services/assets/152205968/a815e6ee-72bc-40bd-b72f-29f9f06be729

**Comment by Illegal-Services** [comment] 2023-12-09 15:42
![firefox_2023-12-09_16-41](https://github.com/Illegal-Services/Illegal_Services/assets/62464560/9caecff9-c6a4-4485-a9da-3d27b8a767f4)

this is something that worries me, you couldn't connect on my proxies from v6.1

**Comment by FearlessOfficial** [comment] 2023-12-09 15:42
> ![firefox_2023-12-09_16-41](https://private-user-images.githubusercontent.com/62464560/289282069-9caecff9-c6a4-4485-a9da-3d27b8a767f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzY4NDIsIm5iZiI6MTcwMjEzNjU0MiwicGF0aCI6Ii82MjQ2NDU2MC8yODkyODIwNjktOWNhZWNmZjktYzZhNC00NDg1LWE5ZGEtM2QyN2I4YTc2N2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE1NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNWQ5NDg2Y2U2NmU4NjliZDQ2Yzc5MDFmYjdjMTNhNTY5NmNjYTM0MTMyYzVlYmI0YjRhOTRjYjFjOTJhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PNvd2iVIbv-vZZicXbEhI91VBn7uOpB22HYOERbqZks)
> 
> this is something that worries me, you couldn't connect on my proxies from v6.1.0.0

I don't know what happend with it

**Comment by Illegal-Services** [comment] 2023-12-09 15:43
proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0
https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261

**Comment by FearlessOfficial** [comment] 2023-12-09 15:45
> proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261

Should i test the bat file?

**Comment by FearlessOfficial** [comment] 2023-12-09 15:46
> proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261

![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/c6eb47b9-1e19-408e-82cb-025658c15a46)

**Comment by Illegal-Services** [comment] 2023-12-09 15:47
> > proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261
> 
> Should i test the bat file?

nope, wait for my instructions

**Comment by FearlessOfficial** [comment] 2023-12-09 15:47
> > > proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261
> > 
> > 
> > Should i test the bat file?
> 
> nope, wait for my instructions

Alright

**Comment by Illegal-Services** [comment] 2023-12-09 15:48
> > proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261
> 
> ![image](https://private-user-images.githubusercontent.com/152205968/289282556-c6eb47b9-1e19-408e-82cb-025658c15a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzcwNjUsIm5iZiI6MTcwMjEzNjc2NSwicGF0aCI6Ii8xNTIyMDU5NjgvMjg5MjgyNTU2LWM2ZWI0N2I5LTFlMTktNDA4ZS04MmNiLTAyNTY1OGMxNWE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNTQ2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQyZWRjNmFkMzdjOWFmNmFiMzViYmM3MWUzOTg0ZDNmZDkyOWY1MTc3OTNkNjlkMjkyODE0YjcyNDUwZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zXfAr24vrouhBWWUds43YZ9YBpQFTO5tOqRd1I6Y53Q)

![Illegal_Services_2023-12-09_16-47](https://github.com/Illegal-Services/Illegal_Services/assets/62464560/01fe82a6-b6c0-462e-8788-ab3addfea8af)


yeah and there it should shows up that instead ^^

**Comment by FearlessOfficial** [comment] 2023-12-09 15:48
> > > proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/152205968/289282556-c6eb47b9-1e19-408e-82cb-025658c15a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzcwNjUsIm5iZiI6MTcwMjEzNjc2NSwicGF0aCI6Ii8xNTIyMDU5NjgvMjg5MjgyNTU2LWM2ZWI0N2I5LTFlMTktNDA4ZS04MmNiLTAyNTY1OGMxNWE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNTQ2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQyZWRjNmFkMzdjOWFmNmFiMzViYmM3MWUzOTg0ZDNmZDkyOWY1MTc3OTNkNjlkMjkyODE0YjcyNDUwZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zXfAr24vrouhBWWUds43YZ9YBpQFTO5tOqRd1I6Y53Q)
> 
> ![Illegal_Services_2023-12-09_16-47](https://private-user-images.githubusercontent.com/62464560/289282642-01fe82a6-b6c0-462e-8788-ab3addfea8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzcxOTksIm5iZiI6MTcwMjEzNjg5OSwicGF0aCI6Ii82MjQ2NDU2MC8yODkyODI2NDItMDFmZTgyYTYtYjZjMC00NjJlLTg3ODgtYWIzYWRkZmVhOGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE1NDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYmI4OTRjNDA3NjliYzY0MDZkYzE0N2E3NDY2M2I0MTYyYjQ2NTJmNGEyNmZiN2U0MGUyYjFiZThhZjQ3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8rQ4YYozgr3j-YKzUBun4gVDhzL3aVzQDC6DModaQg)
> 
> yeah and there it should shows up that instead ^^ (github.com) or another

i tried the web one and github one but still same error

**Comment by Illegal-Services** [comment] 2023-12-09 15:49
alright let's try to makes you download the latest version of IS and see if the error still happends

**Comment by FearlessOfficial** [comment] 2023-12-09 15:49
> > > > proxies in IS are referenced as git repositories where the project is hosted, those are the ones from v1.9.0.0 https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat#L254C1-L254C261
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/152205968/289282556-c6eb47b9-1e19-408e-82cb-025658c15a46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzcwNjUsIm5iZiI6MTcwMjEzNjc2NSwicGF0aCI6Ii8xNTIyMDU5NjgvMjg5MjgyNTU2LWM2ZWI0N2I5LTFlMTktNDA4ZS04MmNiLTAyNTY1OGMxNWE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNTQ2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQyZWRjNmFkMzdjOWFmNmFiMzViYmM3MWUzOTg0ZDNmZDkyOWY1MTc3OTNkNjlkMjkyODE0YjcyNDUwZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zXfAr24vrouhBWWUds43YZ9YBpQFTO5tOqRd1I6Y53Q)
> > 
> > 
> > ![Illegal_Services_2023-12-09_16-47](https://private-user-images.githubusercontent.com/62464560/289282642-01fe82a6-b6c0-462e-8788-ab3addfea8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzcxOTksIm5iZiI6MTcwMjEzNjg5OSwicGF0aCI6Ii82MjQ2NDU2MC8yODkyODI2NDItMDFmZTgyYTYtYjZjMC00NjJlLTg3ODgtYWIzYWRkZmVhOGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE1NDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYmI4OTRjNDA3NjliYzY0MDZkYzE0N2E3NDY2M2I0MTYyYjQ2NTJmNGEyNmZiN2U0MGUyYjFiZThhZjQ3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8rQ4YYozgr3j-YKzUBun4gVDhzL3aVzQDC6DModaQg)
> > yeah and there it should shows up that instead ^^ (github.com) or another
> 
> i tried the web one and github one but still same error

could this affect it? 
![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/ca36be90-5cf8-4c1d-b39a-55e7b2ed6f31)

**Comment by FearlessOfficial** [comment] 2023-12-09 15:50
> alright let's try to makes you download the latest version of IS and see if the error still happends

alright

**Comment by Illegal-Services** [comment] 2023-12-09 15:50
download that and try to runs it, see if it works or not:
https://github.com/Illegal-Services/Illegal_Services/archive/refs/heads/main.zip

**Comment by Illegal-Services** [comment] 2023-12-09 15:51
Yeah maybe, portmaster can be the problem, try disabling it too

**Comment by FearlessOfficial** [comment] 2023-12-09 15:51
> Yeah maybe, portmaster can be the problem, try disabling it too

alright

**Comment by FearlessOfficial** [comment] 2023-12-09 15:51
> download that and try to runs it, see if it works or not: https://github.com/Illegal-Services/Illegal_Services/archive/refs/heads/main.zip

okay

**Comment by FearlessOfficial** [comment] 2023-12-09 15:53
> download that and try to runs it, see if it works or not: https://github.com/Illegal-Services/Illegal_Services/archive/refs/heads/main.zip

nope 
![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/01e9ac4f-955c-4299-9e29-c7ff03ccece3)
i try disable the port master

**Comment by Illegal-Services** [comment] 2023-12-09 15:53
okay good, at least now I know i can work on the latest version and not review the old source code from v6.9.0.0

**Comment by Illegal-Services** [comment] 2023-12-09 15:54
and that error is not even accurate because it is indeed the latest version running, definitively needs a fix for that

**Comment by FearlessOfficial** [comment] 2023-12-09 15:55
alright i have to reboot bc of the port master so brb

**Comment by Illegal-Services** [comment] 2023-12-09 15:56
oki

**Comment by FearlessOfficial** [comment] 2023-12-09 16:00
> oki

wait a bit 
![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/88f85b82-bea4-4f2c-82b9-b0bf1e3abe52)

**Comment by FearlessOfficial** [comment] 2023-12-09 16:02
> > oki
> 
> wait a bit ![image](https://private-user-images.githubusercontent.com/152205968/289285494-88f85b82-bea4-4f2c-82b9-b0bf1e3abe52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzc5NDIsIm5iZiI6MTcwMjEzNzY0MiwicGF0aCI6Ii8xNTIyMDU5NjgvMjg5Mjg1NDk0LTg4Zjg1YjgyLWJlYTQtNGYyYy04MmI5LWIwYmYxZTNhYmU1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNjAwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2ZhMTQxYjlhZGZhNzk5NGY4NDEwY2JlYjU5NDM3ZTdhYzIyMjAyMTg1OTNlNWE0YTljNGFmYjNmMTdjZWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FR7p5DWgK-4lkcfwrFVKzOtGSV5z-BWN4uDbMmINUKc)

oh yep it did work

**Comment by FearlessOfficial** [comment] 2023-12-09 16:02
![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/298d5cf5-fd85-44ab-8252-87cc295cecca)
just uhh am still on old version am i?

**Comment by Illegal-Services** [comment] 2023-12-09 16:04
v6.1.9.5 is the latest version

**Comment by FearlessOfficial** [comment] 2023-12-09 16:05
> v6.1.9.5 is the latest version

oh :D

well thanks again :>
Id i could give you rate it whould be 5/100

**Comment by Illegal-Services** [comment] 2023-12-09 16:05
a rate on what

**Comment by Illegal-Services** [comment] 2023-12-09 16:06
it seems like IS errors are not perfect even on latest version, I have to find the problems, be able to reproduce them and add correct error messages

**Comment by FearlessOfficial** [comment] 2023-12-09 16:06
> a rate on what

you a nice person and you at least help ppl

**Comment by Illegal-Services** [comment] 2023-12-09 16:07
so 5 / 100 is not a lot, do you mean 95/100 ? xD

**Comment by FearlessOfficial** [comment] 2023-12-09 16:07
> it seems like IS errors are not perfect even on latest version, I have to find the problems, be able to reproduce them and add correct error messages

Alrighty good luck then :>
Just have a break and don't push yourself

**Comment by FearlessOfficial** [comment] 2023-12-09 16:07
> so 5 / 100 is not a lot, do you mean 95/100 ? xD

yes :D

**Comment by Illegal-Services** [comment] 2023-12-09 16:07
lmao thanks and I'll try my best

**Comment by Illegal-Services** [comment] 2023-12-09 16:07
ty for reporting the issue, it actually helped

**Comment by FearlessOfficial** [comment] 2023-12-09 16:09
> ty for reporting the issue, it actually helped

Np i hope you fix it 👍 just don't stay too late on pc :D

**Comment by Illegal-Services** [comment] 2023-12-09 16:10
well, i will to fix that xD

**Comment by Illegal-Services** [comment] 2023-12-09 16:10
I'll let you know when I think the issue wil get a correct error message

**Comment by FearlessOfficial** [comment] 2023-12-09 16:10
> I'll let you know when the issue wil get a correct error message

Alright

**Comment by FearlessOfficial** [comment] 2023-12-09 16:12
Alight i have to go to the toilet :D so

gooooodbye i hope we talk again :D
If i found some more bugs or maybe even some other stuff

**Comment by Illegal-Services** [comment] 2023-12-09 16:13
have fun in the toilets xD

**Comment by FearlessOfficial** [comment] 2023-12-09 16:13
> have fun in the toilets xD

XD :D

**Comment by Illegal-Services** [comment] 2023-12-09 16:13
lmao i can't

**Comment by FearlessOfficial** [comment] 2023-12-09 16:14
> lmao i can't

:D

**Comment by Illegal-Services** [comment] 2023-12-09 16:14
you are fun :3

**Comment by FearlessOfficial** [comment] 2023-12-09 16:16
> you are fun :3

thanks :]

**Comment by Illegal-Services** [comment] 2023-12-09 16:18
> Alight i have to go to the toilet :D so
> 
> gooooodbye i hope we talk again :D
> If i found some more bugs or maybe even some other stuff
> 
> Then i report it to you 

Okay add me on discord:
mathieudummy

**Comment by FearlessOfficial** [comment] 2023-12-09 16:19
> mathieudummy

oki

**Comment by FearlessOfficial** [comment] 2023-12-09 16:20
> > Alight i have to go to the toilet :D so
> > gooooodbye i hope we talk again :D
> > If i found some more bugs or maybe even some other stuff
> > Then i report it to you
> 
> Okay add me on discord: mathieudummy

ALight i sended my name is just_white_themes

**Comment by Illegal-Services** [comment] 2023-12-09 17:11
bug fixed in build update:
[v6.1.9.6 - 09/12/2023](https://github.com/Illegal-Services/Illegal_Services/commit/2394e21ac3df24b76081c974e63b35c5b2563d87)
source code changes:
https://github.com/Illegal-Services/Illegal_Services/commit/3e53ff6ec2a2c4f16587c660340c0e1cac0f0989

**Closed** 2023-12-09 17:20 UTC
