### ISSUE TITLE
Illegal Services cannot start because it could not determine its output directory.

### ISSUE THREAD

**Issue by b3four** [Illegal-Services/Illegal_Services#23] opened 2022-11-17 16:48 UTC
![image](https://user-images.githubusercontent.com/118468454/202506788-d4fb1b0f-6881-48ca-a0ca-76a14724e371.png)

any idea?

**Comment by Illegal-Services** [comment] 2022-11-18 14:13
Hello, thank you for reporting this problem.
Can you please open a command prompt ([WIN]+[R] > cmd.exe) and run the following command:
`reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v "Personal"`

**Comment by scetchwrites** [comment] 2023-02-22 08:36
still not working for me

**Comment by Illegal-Services** [comment] 2023-02-22 09:03
> still not working for me

Hello, thank you for reporting this problem.
Can you please open a command prompt ([WIN]+[R] > cmd.exe) and run the following command:
`reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v "Personal"`
and report me here the output from this command.

**Comment by scetchwrites** [comment] 2023-02-22 09:07
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
    Personal    REG_SZ    C:\Users\DD\OneDrive\Documents

**Comment by Illegal-Services** [comment] 2023-02-22 09:09
ahhh... One Drive... Well I'll look at that issue this evening, thanks for the report!

**Comment by scetchwrites** [comment] 2023-02-22 09:10
thanks!! lmk

**Comment by Illegal-Services** [comment] 2023-02-22 09:38
@scetchwrites What version of Windows do you use ?

**Comment by scetchwrites** [comment] 2023-02-22 09:40
im on 11

**Comment by scetchwrites** [comment] 2023-02-22 09:40
i have another pc with 10 on it if thats the prob ??

**Comment by Illegal-Services** [comment] 2023-02-22 09:44
I'm just going to install a VM to run my tests because this problem is specific to windows versions that uses the default path "my documents" with one drive.
I know this is the case for windows 11. With windows 10 you CAN do it but it's not the default configuration from Windows.

**Comment by Illegal-Services** [comment] 2023-02-22 09:48
It will be fixed this evening

**Comment by Illegal-Services** [comment] 2023-02-24 11:56
sorry late reply, I'm not able to reproduce the problem on a VM. OneDrive is not being the default "My Documents" folder.

**Comment by Illegal-Services** [comment] 2023-06-16 21:13
The problem is located here, I should create a temporary folder in another place cuz OneDrive or other such "cloud" locations are problematic to store data in.

https://github.com/Illegal-Services/Illegal_Services/blob/7b12c943a719ac38b0ecb196879f5a776b76b5cc/Illegal_Services.bat#L3645

**Comment by Illegal-Services** [comment] 2023-06-17 10:54
This issue should be fixed in version [v6.1.9.0 - 17/06/2023](https://github.com/Illegal-Services/Illegal_Services/commit/49a29590aff2f68a7d52766cc375406e050b7d44).
Re-open the issue if you are still experiencing a problem.

**Closed by Illegal-Services** 2023-06-17 10:54 UTC
Labels: bug, help wanted, good first issue
