### ISSUE TITLE
IS not displaying properly

### ISSUE THREAD

**Issue by SoftieIsVibing** [Illegal-Services/Illegal_Services#29] opened 2023-02-18 15:48 UTC
![image](https://user-images.githubusercontent.com/65833167/219875154-4e6b8a1f-a06c-43f4-820b-0e0422424968.png)
I dont know why but whenever i open IS it just goes like this for some reason
It works and all but navigating the menu is annoying

**Comment by Illegal-Services** [comment] 2023-02-18 15:52
It seems like the font used in that cmd is not the one I personally use. I suggest this is the issue here.

**Comment by SoftieIsVibing** [comment] 2023-02-18 15:55
Ah right, thats weird, it worked it v5.3
Do you have any idea how to fix it?

**Comment by Illegal-Services** [comment] 2023-02-18 17:53
Oh, by the way, this is a duplicate of the issue I myself opened there https://github.com/Illegal-Services/Illegal_Services/issues/10

**Closed** 2023-02-18 18:00 UTC
